server:
  port:
    8767
eureka:
  instance:
    preferIpAddress: true
  client: 
    fetchRegistry: true
    serviceUrl: 
      defaultZone: http://localhost:8761/eureka/eureka
feign:
  hystrix:
    enabled: true
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  data:
    mongodb:
      port: 27017
      username: sapientgaming
      password: sapientgaming
      database: admin-activities
      authentication-database: admin
      host: localhost
ui_url: http://localhost:3000/app
---
spring:
  profiles: performance
  data:
    mongodb:
      host: 10.0.1.159
eureka:
  instance:
 #   instance-id: ${spring.application.name}:${spring.application.instance_id:8060
    ipAddress: 10.0.1.8
  client:
    serviceUrl:
      defaultZone: http://10.0.1.176:8761/eureka/eureka
ui_url: http://18.210.136.97/app
---
spring:
  profiles: staging
  data:
    mongodb:
      host: 10.0.2.204
eureka:
  instance:
  #  instance-id: ${spring.application.name}:${spring.application.instance_id:8060
    ipAddress: 10.0.2.81
  client:
    serviceUrl:
      defaultZone: http://10.0.2.140:8761/eureka/eureka
ui_url: http://18.215.53.195/app
---
spring:
  profiles: production
  data:
    mongodb:
      host: 10.0.1.63
eureka:
  instance:
  #  instance-id: ${spring.application.name}:${spring.application.instance_id:8060
    ipAddress: 10.0.1.108
  client:
    serviceUrl:
      defaultZone: http://10.0.1.12:8761/eureka/eureka
ui_url: http://18.210.136.97/app
