server:
  port: 8061
  servlet:
    context-path: /secure
    
client_id: guest
client_secret: secret
token_validity: 120
oauth_host: http://localhost:8061/secure
ui_url: http://localhost:3000/app
eureka:
  client:
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/eureka
spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  hikari:
    maxLifetime: 120

---
spring:
  profiles: performance
  datasource:
    url: jdbc:postgresql://10.0.1.159:5432/postgres
    username: postgres
    password: postgres

eureka:
  client:
      serviceUrl:
        defaultZone: http://10.0.1.176:8761/eureka/eureka

ui_url: http://52.205.229.238/app
---
spring:
  profiles: staging
  datasource:
    url: jdbc:postgresql://10.0.2.204:5432/user_management
    username: postgres
    password: secretPass

eureka:
  client:
    serviceUrl:
      defaultZone: http://10.0.2.140:8761/eureka/eureka

ui_url: https://beta.gamifylearningcentre.com/app
token_validity: 3600
---
spring:
  profiles: production
  datasource:
    url: jdbc:postgresql://10.0.1.63:5432/user_management

eureka:
  client:
    serviceUrl:
      defaultZone: http://10.0.1.12:8761/eureka/eureka

ui_url: https://app.gamifylearningcentre.com/app
