
server:
  port: 7500

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: gamifylearningcentre@gmail.com
    password: fruneutxwqicovri
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true
  kafka:
    producer:
      bootstrap-servers: http://localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      bootstrap-servers: http://localhost:9092
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"

    listener:
      missing-topics-fatal: false

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  datasource:
    url:  jdbc:postgresql://localhost:5432/notifications
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

topics: "forgetpassword,changepassword,newuser,socialmedia,coursecomplete,startreminder,loginreminder,sendnow,learning,webinar,assessment,leadership,sendnowwebinar,sendnowcontest"

forgetpassword: Forgot your Password?
changepassword: Your Password has changed.
newuser: Welcome to Publicis Sapient Gamification Application
socialmedia: Social Media Alert
coursecomplete: Congratulations, Your Course Certificate is Ready!
startreminder: We haven't seen you in a while.
loginreminder: We haven't seen you in a while.
sendnow: Urgent Reminder.
learning: We have planned a learning course for you!
webinar: Interactive Connect.
assessment: Contest Alert.
leadership: Leadership Connect.
sendnowwebinar: Urgent Reminder.
sendnowcontest: Urgent Reminder.
