server:
  port: 8642

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
feign:
  hystrix:
    enabled: true

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: sahilvora0409@gmail.com
    password: iqjokadimzjnqvhr
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver

changepass: 2
forgetpass: 1
---
spring:
  profiles: staging
  datasource:
    url: jdbc:postgresql://10.0.2.204:5432/user_management
    username: postgres
    password: secretPass

eureka:
  instance:
    ip-address: 10.0.2.81
  client:
    serviceUrl:
      defaultZone: http://10.0.2.140:8761/eureka/eureka
ui_url: https://beta.gamifylearningcentre.com/app
---
spring:
  profiles: production
  datasource:
    url: jdbc:postgresql://10.0.1.63:5432/user_management
    username: user_management
    password: usrmgmt

eureka:
  instance:
    ip-address: 10.0.2.108
  client:
    serviceUrl:
      defaultZone: http://10.0.1.12:8761/eureka/eureka
ui_url: https://app.gamifylearningcentre.com/app
