eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/eureka
    fetchRegistry: true
  instance:
    ip-address: localhost
    preferIpAddress: true
server:
  port: 9200
feign:
  hystrix:
    enabled: true
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/notifications
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
learning: 9
webinar: 10
assessment: 11
leadership: 12
cron-exp: 0 * * * * ?
---
spring:
  profiles: staging
  datasource:
    url: jdbc:postgresql://10.0.2.204:5432/notifications
    username: postgres
    password: secretPass
eureka:
  instance:
    ip-address: 10.0.2.81
  client:
    serviceUrl:
      defaultZone: http://10.0.2.140:8761/eureka/eureka
---
spring:
  profiles: performance
  datasource:
    url: jdbc:postgresql://10.0.1.159:5432/notifications
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create
eureka:
  instance:
    ip-address: 10.0.1.8
  client:
    serviceUrl:
      defaultZone: http://10.0.1.176:8761/eureka/eureka
---
spring:
  profiles: production
  datasource:
    url: jdbc:postgresql://10.0.1.63:5432/notifications
    username: postgres
    password: adInfinitumX
eureka:
  instance:
    ip-address: 10.0.2.108
  client:
    serviceUrl:
      defaultZone: http://10.0.1.12:8761/eureka/eureka
