eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetchRegistry: true
  instance: 
    preferIpAddress: true
server:
  port: 8762
  servlet:
    context-path: /api
feign:
  hystrix:
    enabled: true
oauth_url: http://localhost:8061/secure
client_id: guest
client_secret: secret
user: /user-management-service/api/v1/user/AdminAccess/searchUser,/user-management-service/api/v1/user/UserAccess/**,/admin-activities/nat/getTestimonialsUser,/admin-activities/nat/getNewslettersUser,/admin-activities/getAllActivityByUser/**,/rules-service/get-leaderboard,/rules-service/get-user-achievements,/password-service/change/**,/password-service/changepass/**,/password-service/passcheck/**
admin: /admin-activities/**
open: /password-service/reset-password/**,/password-service/send-mail/**,/password-service/reset/**
---
spring:
  profiles: staging
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.0.2.140:8761/eureka/eureka
oauth_url: http://10.0.2.140:8061/secure
---
spring:
  profiles: performance
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.0.1.176:8761/eureka/eureka
oauth_url: http://52.205.229.238/secure
---
spring:
  profiles: production
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.0.1.12:8761/eureka/eureka
oauth_url: https://10.0.1.12:8061/secure
