eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/eureka
    fetchRegistry: true
  instance: 
    preferIpAddress: true
server:
  port: 8762
  servlet:
    context-path: /api
feign:
  hystrix:
    enabled: true
oauth_url: http://oauth:8061/secure
client_id: guest
client_secret: secret
user: /user-management-service/api/v1/user/AdminAccess/searchUser,/user-management-service/api/v1/user/AdminAccess/updateUser,/user-management-service/api/v1/user/UserAccess/**,/user-management-service/api/v1/profilePictureUpload/**,/admin-activities/storage/getFile/**,/admin-activities/nat/getTestimonialsUser,/admin-activities/nat/getNewslettersUser,/admin-activities/getAllActivityByUser/**,/rules-service/get-leaderboard,/rules-service/get-user-achievements,/branding-service/api/v1/branding/create-certificate,/password-service/change/**,/password-service/changepass/**,/password-service/passcheck/**
admin: /admin-activities/**
open: /password-service/reset-password/**,/password-service/send-mail/**,/password-service/reset/**
---
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  profiles: staging
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.0.2.140:8761/eureka/eureka
oauth_url: http://10.0.2.140:8061/secure
---
spring:
  profiles: performance
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.0.1.176:8761/eureka/eureka
oauth_url: http://52.205.229.238/secure
---
spring:
  profiles: production
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.0.1.12:8761/eureka/eureka
oauth_url: https://10.0.1.12:8061/secure
